// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfd7PL5V_UmHDeiMFwoht2YBxmf2hDOmc',
    appId: '1:39018621045:web:8c045c3c20c5a7797c303c',
    messagingSenderId: '39018621045',
    projectId: 'school-51c12',
    authDomain: 'school-51c12.firebaseapp.com',
    databaseURL: 'https://school-51c12-default-rtdb.firebaseio.com',
    storageBucket: 'school-51c12.firebasestorage.app',
    measurementId: 'G-YG6FYYXFMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7zb17WHKAlZQzWz2rrc6uET7VfRx96Vk',
    appId: '1:39018621045:android:1d42d1ac3112d2507c303c',
    messagingSenderId: '39018621045',
    projectId: 'school-51c12',
    databaseURL: 'https://school-51c12-default-rtdb.firebaseio.com',
    storageBucket: 'school-51c12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtU6tT4m9wgh61tXI9HcGNsbZfUOInwFQ',
    appId: '1:39018621045:ios:a803d1609156968f7c303c',
    messagingSenderId: '39018621045',
    projectId: 'school-51c12',
    databaseURL: 'https://school-51c12-default-rtdb.firebaseio.com',
    storageBucket: 'school-51c12.firebasestorage.app',
    iosBundleId: 'com.example.schoolFls',
  );
}
