workflows:
  ios-release:
    name: iOS Release
    environment:
      vars:
        SHOREBIRD_TOKEN:
          secure: EncryptedOrSetInUI  # لو محتاج Shorebird token للنشر
    triggering:
      events:
        - push
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Ensure CocoaPods is installed
        script: |
          if ! command -v pod &> /dev/null; then
            echo "CocoaPods not found, installing..."
            sudo gem install cocoapods
          else
            echo "CocoaPods already installed"
          fi
      - name: iOS pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/**/*.ipa
