name: school_fls
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  file_picker: ^10.2.1
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/intro/paernt.png
    - assets/intro/teacher.png  
    - assets/intro/student.png
    - assets/intro/admin.png
    - assets/teachers/
    - assets/teachers/attendance.png
    - assets/teachers/table.png
    - assets/teachers/stage.png
    - assets/teachers/permission.png
    - assets/teachers/department chat.png
    - assets/teachers/myclasses.png
    - assets/teachers/break.png
    - assets/teachers/logo.png